name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                    pip install ruff pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build docs
        run: |
          docsrc\make html
      - name: Test with pytest
        run: |
          pytest testing
      - uses: https://github.com/stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated badges
          branch: docs
          commit_user_name: Gitea Actions Bot
          commit_user_email: l-biochemie@biozentrum.uni-wuerzburg.de
          create_branch: true