name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Set up Python
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                    pip install ruff pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build docs
        uses: https://github.com/uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
        with:
          branch: main
          dir_docs: docsrc
      - name: Test with pytest
        run: |
          mkdir -p tests/badges
          pytest tests
          ls -ltprah tests
          ls -ltprah tests/badges
      - name: Remove gitignore
        run: rm .gitignore
      - name: Push to badges
        uses: https://github.com/stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated badges
          branch: badges
          commit_user_name: Gitea Actions Bot
          commit_user_email: l-biochemie@biozentrum.uni-wuerzburg.de
          create_branch: true
          file_pattern: '**.svg'
          repository: tests/badges
          push_options: --force
          disable_globbing: true