name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Set up Python
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                    pip install ruff pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build docs
        uses: https://github.com/uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
        with:
          branch: main
          dir_docs: docsrc
      - name: Test with pytest
        run: |
          mkdir -p tests/badges
          pytest tests
          ls -ltprah tests
          ls -ltprah tests/badges
      - name: Remove gitignore
        run: |
          rm .gitignore
      - name: Rewrite history
        run: |
          git config user.name "Gitea Actions"
          git config user.email "gitea@bc2-silicon.biozentrum.uni-wuerzburg.de"
          git checkout -b badges
          git add .
          git commit -m 'Updated badges'
          git filter-branch --prune-empty --subdirectory-filter tests/badges/ badges
          git push --force origin badges