name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Set up R with r2u CRAN as Ubuntu Binaries
        run: |
          wget https://raw.githubusercontent.com/eddelbuettel/r2u/master/inst/scripts/add_cranapt_jammy.sh
          sudo chmod +x add_cranapt_jammy.sh
          sudo ./add_cranapt_jammy.sh
          rm add_cranapt_jammy.sh
      - name: Install R dependencies
        run: |
          sudo Rscript --vanilla -e 'install.packages("tmvtnorm", dep=TRUE, repos=c('https://ftp.fau.de/cran/', 'https://cloud.r-project.org'))
      - name: Set up Python
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                    pip install ruff pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate R.conf
        run: |
          PATH_TO_RSCRIPT=$(which Rscript)
          RFUNCTIONS=$(realpath mypackage/RFunctions.R)
          echo -e "R = $PATH_TO_RSCRIPT\nRFUNCTIONS = $RFUNCTIONS" > mypackage/R.conf
      - name: Check R install
        run: |
          python -c "from mypackage import r_helper; r_helper.return_r_path()"
      - name: Build docs
        uses: https://github.com/uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
        with:
          branch: main
          dir_docs: docsrc
      - name: Test with pytest
        run: |
          mkdir -p tests/badges
          pytest -s --verbose -p no:cacheprovider tests
          ls -ltprah tests
          ls -ltprah tests/badges
        env:
          GITHUB_PAT_GITHUB_COM: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Remove gitignore
        run: |
          rm .gitignore
      - name: Rewrite history
        run: |
          git config user.name "Gitea Actions"
          git config user.email "gitea@bc2-silicon.biozentrum.uni-wuerzburg.de"
          git checkout -b badges
          git add .
          git commit -m 'Updated badges'
          git filter-branch --prune-empty --subdirectory-filter tests/badges/ badges
          git push --force origin badges