name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.4.0' # The R version to download (if necessary) and use.
      - name: Install R package requirements
        # libcurl is required for r curl
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                    pip install ruff pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate R.conf
        run: |
          sudo apt-get install -y tree
          pwd
          tree
          PATH_TO_RSCRIPT=$(which Rscript)
          RFUNCTIONS=$(realpath mypackage/RFunctions.R)
          echo -e "R = $PATH_TO_RSCRIPT\nRFUNCTIONS = $RFUNCTIONS" > mypackage/R.conf
          cat mypackage/R.conf
      - name: Check R install
        run: |
          python -c "from mypackage import r_helper; r_helper.return_r_path()"
          Rscript mypackage/RFunctions.R
      - name: Build docs
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
        with:
          branch: main
          dir_docs: docsrc
      - name: Test with pytest
        env:
          PYTHONPATH: .
        run: |
          mkdir -p tests/badges
          pytest -s --verbose -p no:cacheprovider tests
          ls -ltprah tests
          ls -ltprah tests/badges
      - name: Remove gitignore
        run: |
          rm .gitignore
      - name: Rewrite history
        run: |
          git config user.name "Gitea Actions"
          git config user.email "gitea@bc2-silicon.biozentrum.uni-wuerzburg.de"
          git checkout -b badges
          git add .
          git commit -m 'Updated badges'
          git filter-branch --prune-empty --subdirectory-filter tests/badges/ badges
          git push --force origin badges