name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Set up Python
        uses: https://github.com/actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                    pip install ruff pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set up R
        uses: https://github.com/r-lib/actions/setup-r@v2
        with:
            r-version: '4.2.1' # The R version to download (if necessary) and use.
      - name: Generate R.conf
        run: |
          sudo apt-get install -y tree
          pwd
          tree
          PATH_TO_RSCRIPT=$(which Rscript)
          RFUNCTIONS=$(realpath mypackage/RFunctions.R)
          echo -e "R = $PATH_TO_RSCRIPT\nRFUNCTIONS = $RFUNCTIONS" > mypackage/R.conf
          cat mypackage/R.conf
      - name: Check R install
        run: |
          python -c "from mypackage import r_helper; r_helper.return_r_path()"
      - name: Build docs
        uses: https://github.com/uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0
        with:
          branch: main
          dir_docs: docsrc
      - name: Test with pytest
        run: |
          mkdir -p tests/badges
          pytest tests
          ls -ltprah tests
          ls -ltprah tests/badges
      - name: Remove gitignore
        run: |
          rm .gitignore
      - name: Rewrite history
        run: |
          git config user.name "Gitea Actions"
          git config user.email "gitea@bc2-silicon.biozentrum.uni-wuerzburg.de"
          git checkout -b badges
          git add .
          git commit -m 'Updated badges'
          git filter-branch --prune-empty --subdirectory-filter tests/badges/ badges
          git push --force origin badges